# Generated by Django 4.1.5 on 2023-01-23 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bricks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('instance_modified_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('RED', 'RED'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN')], db_index=True, max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBricks',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('instance_created_date', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('instance_modified_date', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('status', models.CharField(choices=[('RED', 'RED'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN')], db_index=True, max_length=24)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bricks',
                'verbose_name_plural': 'historical brickss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='bricks',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['RED', 'YELLOW', 'GREEN'])), name='bricks_bricks_valid_status'),
        ),
    ]
